logging:
  file:
    enable: false
    level: INFO
    path: logs
    rotation: "10 MB"
    retention: "7 days"
  console:
    enable: true
    level: INFO

mineru:
  base_url: https://mineru.net/api/v4
  token: sk-WdkqEeMXevlLxA5nWNmzsFlUSFgKJNYVreVNRpfEg1JoOktB

minio:
  endpoint: localhost:9000
  access_key: minioadmin
  secret_key: minioadmin
  bucket_name: rag-bucket
  secure: false

milvus:
  host: localhost
  port: 19530
  user: root
  password: Milvus

postgre:
  host: localhost
  port: 5433
  user: zhiliao
  password: zhiliao123456
  db_name: enterprise_rag

bailian:
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  api_key: 阿里云百炼平台api key

llm:
  model_name: qwen3.5-flash
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  api_key: 阿里云百炼平台api key

vlm:
  model_name: qwen3.5-flash
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  api_key: 阿里云百炼平台api key